Repository Muhammed-Rahif/Macropad, pull requests merged in 2022-01, with the labels that each got.

#11 test(contexts): update test cases using editor view context
  .github/workflows/coverage-report.yml
  .gitignore
  src/__tests__/App.test.tsx
  src/__tests__/TitleBar.test.tsx
Labels: priority: low, tests

#14 Created README
  README.md
Labels: documentation, priority: high

#15 fix: typo fix
  README.md
Labels: documentation, priority: high

#16 feat(open-file): replace 'open file' code using electron dialog
  src/renderer/App.tsx
  src/renderer/components/MenuBar/MenuBar.tsx
  src/renderer/constants/files.ts
  src/renderer/helpers/editor.ts
Labels: enhancement, priority: high
